# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/CARLOSPC/Documents/Python/Grancentrix/Grandcentrix/Inteface/Main.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GrandCentrix(object):
    def setupUi(self, GrandCentrix):
        GrandCentrix.setObjectName("GrandCentrix")
        GrandCentrix.setWindowModality(QtCore.Qt.WindowModal)
        GrandCentrix.resize(780, 546)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Info.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GrandCentrix.setWindowIcon(icon)
        GrandCentrix.setAutoFillBackground(True)
        GrandCentrix.setStyleSheet("selection-background-color: rgb(170, 85, 255);")
        self.Clear_logger = QtWidgets.QPushButton(GrandCentrix)
        self.Clear_logger.setGeometry(QtCore.QRect(600, 470, 131, 41))
        self.Clear_logger.setObjectName("Clear_logger")
        self.CommandSend = QtWidgets.QLineEdit(GrandCentrix)
        self.CommandSend.setGeometry(QtCore.QRect(20, 90, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.CommandSend.setFont(font)
        self.CommandSend.setInputMethodHints(QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.CommandSend.setObjectName("CommandSend")
        self.Send_Command = QtWidgets.QPushButton(GrandCentrix)
        self.Send_Command.setGeometry(QtCore.QRect(20, 130, 111, 31))
        self.Send_Command.setObjectName("Send_Command")
        self.Clear_command = QtWidgets.QPushButton(GrandCentrix)
        self.Clear_command.setGeometry(QtCore.QRect(150, 130, 111, 31))
        self.Clear_command.setObjectName("Clear_command")
        self.label = QtWidgets.QLabel(GrandCentrix)
        self.label.setGeometry(QtCore.QRect(20, 70, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Logger_writting = QtWidgets.QTextBrowser(GrandCentrix)
        self.Logger_writting.setGeometry(QtCore.QRect(20, 170, 571, 341))
        self.Logger_writting.setObjectName("Logger_writting")
        self.Commandrcv = QtWidgets.QLineEdit(GrandCentrix)
        self.Commandrcv.setEnabled(True)
        self.Commandrcv.setGeometry(QtCore.QRect(390, 90, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Commandrcv.setFont(font)
        self.Commandrcv.setAutoFillBackground(False)
        self.Commandrcv.setStyleSheet("background-color: rgb(170, 85, 255);")
        self.Commandrcv.setAlignment(QtCore.Qt.AlignCenter)
        self.Commandrcv.setReadOnly(True)
        self.Commandrcv.setObjectName("Commandrcv")
        self.label_2 = QtWidgets.QLabel(GrandCentrix)
        self.label_2.setGeometry(QtCore.QRect(390, 70, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.host_main = QtWidgets.QLineEdit(GrandCentrix)
        self.host_main.setGeometry(QtCore.QRect(610, 120, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.host_main.setFont(font)
        self.host_main.setAutoFillBackground(False)
        self.host_main.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.host_main.setInputMethodHints(QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.host_main.setReadOnly(True)
        self.host_main.setObjectName("host_main")
        self.port_main = QtWidgets.QLineEdit(GrandCentrix)
        self.port_main.setGeometry(QtCore.QRect(610, 200, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.port_main.setFont(font)
        self.port_main.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.port_main.setInputMethodHints(QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.port_main.setObjectName("port_main")
        self.label_3 = QtWidgets.QLabel(GrandCentrix)
        self.label_3.setGeometry(QtCore.QRect(610, 100, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(GrandCentrix)
        self.label_4.setGeometry(QtCore.QRect(610, 180, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.frame = QtWidgets.QFrame(GrandCentrix)
        self.frame.setGeometry(QtCore.QRect(600, 60, 161, 231))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(10)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(40, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.Upload = QtWidgets.QPushButton(self.frame)
        self.Upload.setGeometry(QtCore.QRect(20, 190, 111, 31))
        self.Upload.setStyleSheet("color: rgb(0, 170, 0);")
        self.Upload.setObjectName("Upload")

        self.retranslateUi(GrandCentrix)
        QtCore.QMetaObject.connectSlotsByName(GrandCentrix)

    def retranslateUi(self, GrandCentrix):
        _translate = QtCore.QCoreApplication.translate
        GrandCentrix.setWindowTitle(_translate("GrandCentrix", "GrandCentrix App"))
        self.Clear_logger.setText(_translate("GrandCentrix", "Clear Logger"))
        self.Send_Command.setText(_translate("GrandCentrix", "Send"))
        self.Clear_command.setText(_translate("GrandCentrix", "Clear"))
        self.label.setText(_translate("GrandCentrix", "Command Send"))
        self.label_2.setText(_translate("GrandCentrix", "Received Command"))
        self.label_3.setText(_translate("GrandCentrix", "HOST"))
        self.label_4.setText(_translate("GrandCentrix", "PORT"))
        self.label_5.setText(_translate("GrandCentrix", "IP CONFIG."))
        self.Upload.setText(_translate("GrandCentrix", "Upload"))


